services:
    misago:
        container_name: misago-forum
        image: yiove/misago-forum:1.0
        build: misago
        restart: unless-stopped
        ports:
            - "28000:3031"
        networks:
            - 1panel-network
        environment:
            - POSTGRES_HOST=${MISAGO_POSTGRES_HOST:-postgres-15}
            - POSTGRES_DB=${MISAGO_POSTGRES_DB:-misagodb}
            - POSTGRES_USER=${MISAGO_POSTGRES_USER:-misagodb}
            - POSTGRES_PASSWORD=${MISAGO_POSTGRES_PASSWORD:-misagodbpassword}
            - SSL_POLICY=Mozilla-Modern
            - VIRTUAL_PROTO=uwsgi
        env_file:
            - ./config/misago.env
            - ./config/.env
        volumes:
            - ./misago/media:/misago/media:z
            - ./misago/static:/misago/static:z
            - ./misago/avatargallery:/misago/avatargallery:ro
            - ./misago/theme:/misago/theme:ro
            - ./backups:/misago/backups:Z
            - ./logs:/misago/logs:z

    celery-worker:
        container_name: misago-celery-worker
        image: yiove/misago-celery-worker:1.0
        build: misago
        command: celery -A misagodocker worker --loglevel=info
        restart: unless-stopped
        networks:
            - 1panel-network
        environment:
            - POSTGRES_HOST=${MISAGO_POSTGRES_HOST:-postgres-15}
            - POSTGRES_DB=${MISAGO_POSTGRES_DB:-misagodb}
            - POSTGRES_USER=${MISAGO_POSTGRES_USER:-misagodb}
            - POSTGRES_PASSWORD=${MISAGO_POSTGRES_PASSWORD:-misagodbpassword}
        env_file:
            - ./config/misago.env
            - ./config/.env
        volumes:
            - ./misago/media:/misago/media:z
            - ./misago/static:/misago/static:z
            - ./misago/theme:/misago/theme:ro
            - ./logs:/misago/logs:z

networks:
    1panel-network:
        external: true
        name: 1panel-network

