services:
    misago:
        container_name: misago-forum
        image: yiove/misago:1.0
        build: misago
        restart: unless-stopped
        ports:
            - "23456:3031"
        networks:
            - 1panel-network
        env_file:
            - ./config/misago.env
            - config.env
        volumes:
            - ./misago/media:/misago/media:z
            - ./misago/static:/misago/static:z
            - ./misago/avatargallery:/misago/avatargallery:ro
            - ./misago/theme:/misago/theme:ro
            - ./backups:/misago/backups:Z
            - ./logs:/misago/logs:z
            - ./misago/misagodocker:/misago/misagodocker:Z
            - ./misago/uwsgi.ini:/misago/uwsgi.ini:Z

    celery-worker:
        container_name: misago-celery-worker
        image: yiove/misago:1.0
        command: celery -A misagodocker worker --loglevel=info
        restart: unless-stopped
        networks:
            - 1panel-network
        env_file:
            - ./config/misago.env
            - config.env
        volumes:
            - ./misago/media:/misago/media:z
            - ./misago/static:/misago/static:z
            - ./misago/theme:/misago/theme:ro
            - ./logs:/misago/logs:z

networks:
    1panel-network:
        external: true
        name: 1panel-network

